resources:
  containers:
  - container: u18
    image: yugabytedb/yb_build_infra_ubuntu1804:v2019-04-30T20_16_36_mikhail

jobs:
- job: RunInContainer
  pool:
    vmImage: 'ubuntu-16.04'
  timeoutInMinutes: 0

  strategy:
    matrix:
      ubuntu18:
        containerResource: u18

  container: $[ variables['containerResource'] ]

  steps:
    - script: |
        set -euxo pipefail
        echo $( yugabyte.githubToken )
        repo_dir=$PWD
        tag=v0.$( git rev-list --count HEAD )
        mkdir ~/linuxbrew_versions
        cd ~/linuxbrew_versions
        #"$repo_dir/linuxbrew-clone-and-build-all.sh"
        touch foo
        touch bar
        tar cvzf myarchive.tar.gz foo bar
        create_release_cmd=( hub release create "$tag" -m "Release $tag" )
        for f in *.tar.gz; do
          create_release_cmd+=( -a "$PWD/$f" )
        done
        cd "$repo_dir"
        "${create_release_cmd[@]}"
      env:
        GITHUB_TOKEN: $(yugabyte.githubToken)
        
