
trigger:
  - master

stages:
  - stage: main_stage
    jobs: 
      - job: main_job
        pool:
          vmImage: 'Ubuntu-16.04'
        timeoutInMinutes: 0
        steps:
          - script: |
              sudo apt-get install -y build-essential golang
              go get github.com/aktau/github-release
              git tag v$(date +%Y%m%dT%H%M%S)
              ~/go/bin/github-release
            displayName: 'Install dependencies'

          - script: |
              repo_dir=$PWD
              mkdir ~/linuxbrew_versions
              cd ~/linuxbrew_versions
              "$repo_dir/linuxbrew-clone-and-build-all.sh"
            displayName: 'Build Linuxbrew'
