resources:
  containers:
  - container: u18
    image: yugabytedb/yb_build_infra_ubuntu1804:v2019-04-30T20_16_36_mikhail

jobs:
- job: RunInContainer
  pool:
    vmImage: 'ubuntu-16.04'
  timeoutInMinutes: 0

  strategy:
    matrix:
      ubuntu18:
        containerResource: u18

  container: $[ variables['containerResource'] ]

  steps:
    - script: |
        repo_dir=$PWD
        mkdir ~/linuxbrew_versions
        cd ~/linuxbrew_versions
        tag=v0.$( git rev-list --count HEAD )
        git tag "$tag"
        hub release create "$tag" -m "Release $tag"
        "$repo_dir/linuxbrew-clone-and-build-all.sh"
      env:
        GITHUB_TOKEN: $(yugabyte.githubToken)
        
