resources:
  containers:
  - container: centos7
    image: yugabytedb/yb_build_infra_centos7:v2019-09-01T14_58_09_mbautin

jobs:
- job: RunInContainer
  pool:
    vmImage: 'ubuntu-16.04'
  timeoutInMinutes: 0

  strategy:
    matrix:
      ubuntu18:
        containerResource: u18

  container: $[ variables['containerResource'] ]

  steps:
    - script: |
        set -euxo pipefail
        repo_dir=$PWD
        timestamp=$( date +%Y-%m-%dT%H_%M_%S )
        num_commits=$( git rev-list --count HEAD )
        num_commits=$( printf "%06d" $num_commits )
        tag=v${timestamp}__${num_commits}__$( git rev-parse HEAD )
        top_dir_name=yb-linuxbrew-$tag
        linuxbrew_dir=/opt/yugabyte-build/linuxbrew-versions/$top_dir_name
        touch "$linuxbrew_dir"/foo
        touch "$linuxbrew_dir"/far
        tar cvzf "$top_dir_name.tar.gz" "$linuxbrew_dir"
        create_release_cmd=( hub release create "$tag" -m "Release $tag" )
        for f in *.tar.gz; do
          create_release_cmd+=( -a "$PWD/$top_dir_name.tar.gz" )
        done
        "${create_release_cmd[@]}"
        # "$repo_dir/linuxbrew-clone-and-build-all.sh"
        # cd "$repo_dir"
      env:
        GITHUB_TOKEN: $(yugabyte.githubToken)
