resources:
  containers:
  - container: centos7
    image: yugabytedb/yb_build_infra_centos7:v2019-09-01T14_58_09_mbautin

jobs:
- job: RunInContainer
  pool:
    vmImage: 'ubuntu-16.04'
  timeoutInMinutes: 0

  strategy:
    matrix:
      centos7:
        containerResource: centos7

  container: $[ variables['containerResource'] ]

  steps:
    - script: |
        sudo mkdir -p /opt/yugabyte-build
        sudo chown yugabyte-ci /opt/yugabyte-build
        sudo -u yugabyte-ci -i ./build-and-release.sh
      env:
        GITHUB_TOKEN: $(yugabyte.githubToken)
